-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgzs4eR6nk8v8PRduu
i9lCRuh04VqdFvHDzwID7DYdc2GgCgYIKoZIzj0DAQehRANCAASP5hNMYnbL9b60
0gZg8XLBqIdwFLVfEIwScSPDnUjfV6aKkfNjqPwDRgH/ZUbuKsPWvQ/0q6U6JyBf
Q/rYajHC
-----END PRIVATE KEY-----