name: youdu
description: A new Flutter project.
publish_to: "none"

version: 1.3.1+67

environment:
  sdk: ">=2.18.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  rxdart: ^0.27.3
  http: ^0.13.4
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  google_sign_in: ^5.2.4
  flutter_facebook_auth: ^4.4.1+1
  firebase_auth: ^3.11.2
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^4.0.2
  google_maps_flutter: ^2.2.2
  platform: ^3.1.0
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  page_transition: ^2.0.9
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  yandex_geocoder: ^2.0.2
  image_picker: ^0.8.6
  mime: ^1.0.1
  dio: ^4.0.6
  sign_in_with_apple: ^4.1.0
  map_picker: ^0.0.3
  url_launcher: ^6.1.6
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^13.0.4
  firebase_core: ^1.24.0
  flutter_local_notifications: ^12.0.0
  path_provider: ^2.0.10
  youtube_player_flutter: ^8.1.0
  flutter_inappwebview: ^5.4.4+3
  share_plus: ^4.0.4
  sqflite: ^2.0.2+1
  dotted_line: ^3.1.0
  fluster: ^1.2.0
  slide_to_confirm: ^1.1.0
  action_slider: ^0.6.0
  lottie: ^1.3.0
  blur: ^3.0.0
  device_info_plus: ^7.0.0
  flutter_udid: ^2.0.0
  # flutter_masked_text: ^0.8.0
  webview_flutter: ^3.0.4
  email_validator: ^2.1.17
  dotted_border: ^2.0.0+2
  scrollable_positioned_list: ^0.3.5
  internet_connection_checker: ^1.0.0+1
  image_cropper: ^3.0.1
  flutter_linkify: ^5.0.2
  currency_textfield_2: ^2.5.0
  currency_text_input_formatter: ^2.1.8
  dotted_dashed_line: ^0.0.3
  fluttertoast: ^8.1.1
  otp_autofill: ^2.1.0
  provider: ^6.0.5
  intl: ^0.17.0
  firebase_crashlytics: ^2.9.0
  sentry_flutter: ^6.20.1
  sentry_logging: ^6.20.1
  logging: ^1.0.2
  in_app_update: ^4.0.1
  upgrader: ^6.5.0
  firebase_performance: ^0.8.3+3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_auth: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

dependency_overrides:
  intl: ^0.18.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/menu/
    - assets/i18n/
    - assets/icons/
    - assets/images/
    - assets/anim/
    - assets/fonts/
    - shorebird.yaml
  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proxima/ProximaNova-Black.otf
          weight: 900
        - asset: assets/fonts/proxima/ProximaNova-Bold.otf
          weight: 700
        - asset: assets/fonts/proxima/ProximaNova-Extrabold.otf
          weight: 800
        - asset: assets/fonts/proxima/ProximaNovaAlt-Light.otf
          weight: 300
        - asset: assets/fonts/proxima/ProximaNova-Bold.otf
          weight: 500
        - asset: assets/fonts/proxima/ProximaNova-Regular.otf
          weight: 400
        - asset: assets/fonts/proxima/ProximaNovaAlt-Bold.otf
          weight: 600
        - asset: assets/fonts/proxima/ProximaNova-Thin.otf
          weight: 200
        - asset: assets/fonts/proxima/ProximaNovaAlt-Thin.otf
          weight: 100
